;规则集定义

;广告、隐私、应用商店下载
ruleset=拦截,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanProgramAD.list
ruleset=拦截,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/BanEasyPrivacy.list



;阿里系,LOL、Destiny2、Emby、cfEmby、涩涩、DIY
ruleset=直连,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Alibaba/Alibaba.list
ruleset=直连,https://raw.githubusercontent.com/KIKUMeiZiZi/clashGZ/refs/heads/main/LOL.list
ruleset=命运2,https://raw.githubusercontent.com/KIKUMeiZiZi/clashGZ/refs/heads/main/Destiny2.list
ruleset=直连,https://raw.githubusercontent.com/KIKUMeiZiZi/clashGZ/refs/heads/main/Emby.list
ruleset=cfEmby,https://raw.githubusercontent.com/KIKUMeiZiZi/clashGZ/refs/heads/main/cfEmby.list
ruleset=全球加速,https://raw.githubusercontent.com/KIKUMeiZiZi/clashGZ/refs/heads/main/seqing.list
ruleset=全球加速,https://raw.githubusercontent.com/KIKUMeiZiZi/clashGZ/refs/heads/main/DIY.list

;Instagram,GoogleFCM,TikTok,Youtube,Discord,OpenAi,GitHub%2,谷歌%2,Copilot,OneDrive,Microsoft,苹果服务,telegram,Speedtest,Youtube,Netflix,
ruleset=全球加速,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Instagram/Instagram.yaml
ruleset=全球加速,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GoogleFCM/GoogleFCM.list
ruleset=TikTok,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/TikTok/TikTok.yaml
ruleset=全球加速,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/YouTube.list
ruleset=全球加速,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Discord/Discord.list
ruleset=全球加速,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Twitter.list
ruleset=OpenAi,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/OpenAi.list
ruleset=全球加速,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GitHub/GitHub.list
ruleset=全球加速,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GitHub/GitHub.yaml
ruleset=直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GoogleCN.list
ruleset=全球加速,https://raw.githubusercontent.com/KIKUMeiZiZi/clashGZ/main/google.list
ruleset=全球加速,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Bing.list
ruleset=全球加速,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/OneDrive/OneDrive.list
ruleset=Microsoft,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Ruleset/Microsoft.list
ruleset=苹果服务,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Apple.list
ruleset=全球加速,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Telegram/Telegram.list
ruleset=全球加速,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Speedtest/Speedtest.list
ruleset=全球加速,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/YouTube.list
ruleset=奈飞节点,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Netflix.list

;游戏平台：Steam,Epic,Origin,Ubisoft,Sony,任天堂
ruleset=游戏加速,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Steam.list
ruleset=游戏加速,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Epic.list
ruleset=游戏加速,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Origin.list
ruleset=游戏加速,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Ubisoft/Ubisoft.yaml
ruleset=索尼,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Sony.list
ruleset=任天堂,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Nintendo.list

;国内媒体,全球媒体,
ruleset=直连,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/ChinaMedia/ChinaMedia.list
ruleset=全球加速,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GlobalMedia/GlobalMedia_Classical.yaml
ruleset=全球加速,https://raw.githubusercontent.com/ddgksf2013/Filter/master/Streaming.list
ruleset=全球加速,https://raw.githubusercontent.com/ConnersHua/RuleGo/master/Surge/Ruleset/Proxy.list

;国内等等/BT下载
ruleset=直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list
ruleset=直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list
ruleset=直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Download.list
ruleset=直连,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/China/China.list
ruleset=直连,[]GEOIP,CN,no-resolve
ruleset=兜底分流,[]FINAL



;策略组定义
custom_proxy_group=全球加速`select`[]自动选择`[]HK香港节点`[]TW台湾节点`[]JP日本节点`[]SG新加坡节点`[]US美国节点`[]纯净`[]手动选择`[]涡流`[]DIRECT
custom_proxy_group=苹果服务`select`[]DIRECT`[]HK香港节点`[]TW台湾节点`[]JP日本节点`[]SG新加坡节点`[]US美国节点`[]手动选择
custom_proxy_group=Microsoft`select`[]HK香港节点`[]TW台湾节点`[]无限流`[]本地
custom_proxy_group=cfEmby`select`[]福利`[]无限流`[]KG`[]本地`[]HK香港节点`[]TW台湾节点`[]SG新加坡节点`[]手动选择`[]DIRECT
custom_proxy_group=游戏加速`select`[]DIRECT`[]HK香港节点`[]TW台湾节点`[]手动选择
custom_proxy_group=命运2`select`[]DIRECT`[]HK香港节点`[]TW台湾节点`[]GM香港`[]本地`[]手动选择
custom_proxy_group=TikTok`select`[]TW台湾节点`[]JP日本节点`[]SG新加坡节点`[]US美国节点`[]HK香港节点`[]手动选择
custom_proxy_group=OpenAi`select`[]US美国节点`[]手动选择
custom_proxy_group=直连`select`[]DIRECT`[]HK香港节点`[]TW台湾节点`[]手动选择
custom_proxy_group=兜底分流`select`[]DIRECT`[]HK香港节点`[]TW台湾节点`[]手动选择`[]涡流
custom_proxy_group=拦截`select`[]REJECT`[]DIRECT

;节点细化
custom_proxy_group=本地`select`(?=.*(本地| 0))^((?!(流媒体)).)*$
custom_proxy_group=GM香港`fallback`(?=.*(港))^((?!(-香|本地|HY2|VLESS)).)*$`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=福利`load-balance`(?=.*(港|台))^((?!(-1|01|02|03|流媒体|本地|HY2|VLESS)).)*$`http://www.gstatic.com/generate_204`300,,1
custom_proxy_group=无限流`url-test`(?=.*(港|台|越))^((?!(-香|-台|-越|流媒体|本地|HY2|VLESS)).)*$`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=涡流`url-test`(?=.*(-0))^.*$`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=KG`url-test`(?=.*(流媒体))^((?!(日|新加坡|韩|美)).)*$`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=索尼`select`.*
custom_proxy_group=任天堂`select`.*
custom_proxy_group=奈飞节点`select`.*
custom_proxy_group=手动选择`select`.*
custom_proxy_group=纯净`select`(2x|4x)
custom_proxy_group=自动选择`url-test`^(.(?!(-0|套餐|流媒体)))*$`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=HK香港节点`url-test`(?=.*(港))^((?!(-0|流媒体|本地|HY2|VLESS)).)*$`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=TW台湾节点`url-test`(?=.*(台))^((?!(-0|流媒体|本地|HY2|VLESS)).)*$`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=JP日本节点`url-test`(?=.*(日本))^((?!(-0|4x|流媒体)).)*$`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=SG新加坡节点`url-test`(?=.*(新加))^((?!(-0|流媒体)).)*$`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=US美国节点`url-test`(?=.*(美))^((?!(-0|2x|4x|流媒体)).)*$`http://www.gstatic.com/generate_204`300,,50
























